#standardSQL
select
p.product_id,
p.country_code,
p.product_title,
p.upc,
p.isrc,
p.master_artist,
p.master_artist_id,
p.master_track,
p.master_track_id,
p.master_album,
p.master_album_id,
p.release_artist_id,
p.release_artist,
case when p.project_id = -1 then p.master_artist_id*100 + 1 else p.project_id end as project_id,
p.project_title,
p.project_artist_id,
p.project_artist,
p.project_release_date,
p.first_project_activity_week,
p.r2_project_number,
p.r2_resource_title,
p.r2_resource_version_title,
p.first_release_activity_week,
p.r2_release_title,
p.r2_release_version_title,
p.genre_name,
p.genre_code,
p.sub_genre_name,
p.sub_genre_code,
case when p.label_family_id = 0 then 
  ifnull(ifnull(r2m.label_family_id, sflm.label_family_id), 0)
else p.label_family_id end as label_family_id,
case when p.label_family_id = 0 then 
  ifnull(ifnull(r2m.label_family_name, sflm.label_family_name), 'UNKNOWN')
else p.label_family_name end as label_family_name,
p.r2_company,
p.r2_division,
p.r2_label_id,
p.r2_label,
p.sap_hfm_rep_owner,
p.sap_segment_code,
p.sap_segment_name,
p.sap_profit_center,
p.sap_financial_label_code,
p.sap_financial_label_name,
p.sap_sales_rep_owner,
p.sap_source_rep_owner,
p.sap_domestic_flag,
p.product_life_cycle,
p.product_release_date,
p.earliest_resource_release_date,
p.primary_upc,
p.product_group,
p.configuration_description,
p.configuration_code,
p.duration,
p.number_of_tracks,
p.pc_notice_year,
p.soundtrack_ind,
p.earliest_master_track_release_date,
p.earliest_project_release_date,
p.load_datetime
from `{{ var.value.metadata_src }}.product` p
left outer join `{{ var.value.metadata_dst }}.label_family_r2_label_map` r2m on p.r2_label_id = r2m.r2_label_id
left outer join `{{ var.value.metadata_dst }}.label_family_sap_financial_label_map` sflm on p.sap_financial_label_code = sflm.sap_financial_label_code 

