select 
period_marker,	
period,
territory_marker,	
territory,
partner,
label_marker,	
label,
upc,
project_id,
units,	
physical_album_units,	
digital_album_units,	
digital_track_units,	
stream_units,	
album_adjusted_units,	
stream_album_adjusted_units,	
digital_track_album_adjusted_units,	
euro,	
physical_album_euro,	
digital_album_euro,	
digital_track_euro,	
stream_euro,
digital_album_preorder_units,	
digital_album_album_adjusted_units,
physical_album_units as physical_album_album_adjusted_units,
shard_number,	
load_datetime
from `#src_agg_dataset#.#table#_#shard#`
where _partitiontime = timestamp(@datePartition)
